version: '3'

services:
  app:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file: .env
    restart: always
  db:
    image: postgres:15.3-alpine
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

volumes:
  db:
