"""likes and dislikes difference

Revision ID: d4ea7ee1adb5
Revises: 1353643e567d
Create Date: 2023-07-28 11:14:18.633297

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd4ea7ee1adb5'
down_revision = '1353643e567d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rates', sa.Column('like', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rates', 'like')
    # ### end Alembic commands ###
